services:
  - type: web
    name: metaofmbot
    env: docker
    plan: free
    region: oregon # Adjust if necessary
    dockerfilePath: ./Dockerfile
    envVars:
      - key: BOT_TOKEN
        value: "7788269650:AAHBQ-kl92EjElg6UoRjYK5dcmXVqO2C_aw"
